name: pos_portal
description: "Pos Portal"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^5.0.2
  sqflite:
  currency_text_input_formatter: ^2.2.3
  custom_sliding_segmented_control: ^1.8.2
  provider:
  lottie: ^3.1.2
  webview_flutter: ^3.0.1
  blue_thermal_printer:
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Black.ttf
          weight: 800
        - asset: fonts/Montserrat-Italic.ttf
          style: italic